version: "2"
services:
  maven-pkg:
    image: maven
    volumes:
      - /home/ubuntu/AWS-ansible/dockerised-java:/project
    working_dir: /project
    command: bash -c "mvn package"

  tomcat-app:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile.tomcat
    image: tomcat:install
    container_name: tomcat-webapp
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/AWS-ansible/dockerised-java/target/DockerExample.war:/opt/tomcat/webapps/ROOT.war
      - /home/ubuntu/AWS-ansible/dockerised-java/target/DockerExample:/opt/tomcat/webapps/ROOT
    command: bash -c "/opt/tomcat/bin/catalina.sh run"

