version: "2"
services:
  tomcat-app:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile.tomcat
    image: tomcat:install
    container_name: tomcat-webapp
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /tmp/:/tmp/ 
    command: bash -c "/opt/tomcat/bin/catalina.sh run"

